apiVersion: v1
kind: Pod
metadata:
  name: key-manager-grpc
  labels:
    app: key-manager-grpc
spec: 
  containers:
    - name: key-manager-grpc-container
      image: rayllandersonzup/key-manager-grpc:1.0
      ports: 
        - containerPort: 50051
          name: grpc-server
        - containerPort: 8085
          name: health-check
      env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
      envFrom: 
        - configMapRef: 
            name: key-manager-grpc-confimap