apiVersion: v1
kind: Service
metadata:
  name: key-manager-grpc-svc
spec: 
  selector:
    app: key-manager-grpc
  ports:
    - port: 50051
      name: grpc-server
    - port: 8085
      name: health-check